### PR TITLE
[Bug #475] ProcessTermsForTreeSelect option to include flattenAncestors

### LINKED ISSUE #475: Selektor nenabízí všechny pojmy slovníku při označení definice pojmu v anotátoru
Zkouším v anotátoru tento postup:

1. označím část textu
2. vyberu Označení definice pojmu
3. chci vybrat pojem, který odpovídá definici, ale jde mi vybrat pouze pojmy, které jsou ve slovníku hierarchicky nejvýše, tj. k potomkům se nelze přes selektor dostat

Pracuji na DEV v tomto dokumentu:
[https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-z%C3%A1kona-%C4%8D.-283-202[…]%A1kon-ve-zn%C4%9Bn%C3%AD-k-1.-7.-2024/document/soubor/](https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-z%C3%A1kona-%C4%8D.-283-2021-sb.-stavebn%C3%AD-z%C3%A1kon-ve-zn%C4%9Bn%C3%AD-k-1.-7.-2024/document/zakonyprolidi_cs_2021_283_v20240701.html?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/&fileNamespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/slovn%C3%ADk-z%C3%A1kona-%C4%8D.-283-2021-sb.-stavebn%C3%AD-z%C3%A1kon-ve-zn%C4%9Bn%C3%AD-k-1.-7.-2024/document/soubor/)

### Závažnost problému
2. je to vážný problém

### PR DESCRIPTION
**Pull request by lukaskabc**
resolves #475

### CODE REVIEW

File: src/component/annotator/AnnotatorTermsSelector.tsx [hunk 1]
```diff
@@ -33,17 +33,26 @@ const AnnotatorTermsSelector: React.FC<AnnotatorTermsSelectorProps> = ({
   const { annotatorTerms, vocabulary, terminalStates } = useSelector(
     (state: TermItState) => state
   );
+  const [options, setOptions] = useState([] as Term[]);
```
Comment (ledsoft) [inline src/component/annotator/AnnotatorTermsSelector.tsx]: Do you think it is necessary to store the options in state? They do not change by any actions within the component. If it is for caching reasons, wouldn't memoization make more sense?

File: src/component/annotator/AnnotatorTermsSelector.tsx [hunk 2]
```diff
@@ -33,7 +33,15 @@ const AnnotatorTermsSelector: React.FC<AnnotatorTermsSelectorProps> = ({
   const { annotatorTerms, vocabulary, terminalStates } = useSelector(
     (state: TermItState) => state
   );
-  const [options, setOptions] = useState([] as Term[]);
+
+  const options = useMemo(() => {
+    console.debug("memo");
```
Comment (ledsoft) [inline src/component/annotator/AnnotatorTermsSelector.tsx]: Remove the console logging.

**Review by ledsoft — APPROVED** [review]
LGTM
